package app.bookflow.reader

import android.content.Context
import android.database.Cursor
import android.graphics.Bitmap
import android.graphics.pdf.PdfRenderer
import android.media.MediaPlayer
import android.net.Uri
import android.os.Bundle
import android.os.ParcelFileDescriptor
import android.provider.OpenableColumns
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import app.bookflow.reader.core.data.DocxTextExtractor
import app.bookflow.reader.core.data.RuleBasedSceneDirector
import app.bookflow.reader.core.data.SupabaseVoiceRenderer
import app.bookflow.reader.core.domain.BookDocument
import com.tom_roush.pdfbox.android.PDFBoxResourceLoader
import com.tom_roush.pdfbox.pdmodel.PDDocument
import com.tom_roush.pdfbox.text.PDFTextStripper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);PDFBoxResourceLoader.init(applicationContext);setContent{BookFlowApp()}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun BookFlowApp(){val context=LocalContext.current;var importedBook by remember{mutableStateOf<BookDocument?>(null)};var openedBook by remember{mutableStateOf<BookDocument?>(null)};val launcher=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null){runCatching{context.contentResolver.takePersistableUriPermission(uri,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)};val mime=context.contentResolver.getType(uri).orEmpty();val title=queryDisplayName(context,uri)?:"Libro";val text=when{mime=="text/plain"||title.endsWith(".txt",true)->runCatching{context.contentResolver.openInputStream(uri)?.bufferedReader()?.use{it.readText()}}.getOrNull();mime.contains("wordprocessingml",true)||title.endsWith(".docx",true)->runCatching{context.contentResolver.openInputStream(uri)?.use(DocxTextExtractor::extract)}.getOrNull();else->null};importedBook=BookDocument(uri.toString(),title,mime,text)}};MaterialTheme{Surface(Modifier.fillMaxSize()){if(openedBook!=null)ReaderScreen(openedBook!!){openedBook=null}else Scaffold(topBar={TopAppBar(title={Text("BookFlow")})}){p->LibraryScreen(Modifier.padding(p),importedBook,{launcher.launch(arrayOf("application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"))}){openedBook=it}}}}}
@Composable private fun LibraryScreen(modifier:Modifier,book:BookDocument?,onImport:()->Unit,onOpen:(BookDocument)->Unit){Column(modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Text("Tu biblioteca",style=MaterialTheme.typography.headlineMedium);Text("Lectura · Narración · IA",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold);Button(onClick=onImport){Text("Importar libro")};if(book==null)Box(Modifier.fillMaxWidth().weight(1f),contentAlignment=Alignment.Center){Text("Importa un libro para leerlo o escucharlo con narración IA.")}else Card(Modifier.fillMaxWidth().clickable{onOpen(book)}){Row(Modifier.padding(14.dp),horizontalArrangement=Arrangement.spacedBy(14.dp),verticalAlignment=Alignment.CenterVertically){if(book.isPdf)PdfCover(book.uriString,Modifier.width(105.dp).height(150.dp));Column(Modifier.weight(1f)){Text(cleanBookTitle(book.title),style=MaterialTheme.typography.titleLarge,maxLines=3,overflow=TextOverflow.Ellipsis);Spacer(Modifier.height(6.dp));Text(if(book.isPdf)"PDF · lectura + narración IA" else if(book.textContent!=null)"Listo para narrar" else "Documento importado")}}}}}
@Composable private fun PdfCover(uriString:String,modifier:Modifier){val context=LocalContext.current;val bitmap=remember(uriString){renderPdfPageFromUri(context,uriString,0,.55f)};if(bitmap!=null)Image(bitmap.asImageBitmap(),"Portada",modifier,contentScale=ContentScale.Crop)else Card(modifier){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("PDF")}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun ReaderScreen(book:BookDocument,onBack:()->Unit){val context=LocalContext.current;val director=remember{RuleBasedSceneDirector()};val renderer=remember(context){SupabaseVoiceRenderer(context.applicationContext)};val scope=rememberCoroutineScope();var player by remember{mutableStateOf<MediaPlayer?>(null)};var generating by remember{mutableStateOf(false)};var status by remember{mutableStateOf("Preparando libro…")};var pdfText by remember(book.uriString){mutableStateOf<String?>(null)};var offset by remember(book.uriString){mutableIntStateOf(0)};var autoContinue by remember(book.uriString){mutableStateOf(false)}
LaunchedEffect(book.uriString){if(book.isPdf){pdfText=withContext(Dispatchers.IO){runCatching{extractPdfText(context,book.uriString)}.getOrNull()?.takeIf{it.isNotBlank()}};status=if(pdfText!=null)"PDF listo para narrar." else "Este PDF no contiene texto extraíble."}else status="Listo para narrar."};DisposableEffect(Unit){onDispose{autoContinue=false;runCatching{player?.release()}}};val raw=book.textContent?:pdfText;val narratable=raw?.let(::cleanNarratableText);val progress=if(narratable.isNullOrEmpty())0 else ((offset.toFloat()/narratable.length)*100).toInt().coerceIn(0,100)
var narrateAt:((Int)->Unit)?=null
narrateAt=fun(start:Int){val text=narratable?:return;val chunk=nextNarrationChunk(text,start);if(chunk.text.isBlank()){autoContinue=false;offset=text.length;status="Llegaste al final del libro.";return};generating=true;status="Preparando siguiente tramo…";scope.launch{try{val plan=director.createPlan(chunk.text);val voice=if(plan.speakerId=="narrator_female")FEMALE_VOICE_ID else MALE_VOICE_ID;val segment=renderer.render(plan,voice);runCatching{player?.release()};player=MediaPlayer().apply{setDataSource(segment.localUri);setOnPreparedListener{offset=start;status="Reproduciendo · ${plan.speakerLabel} · ${plan.mood}";it.start()};setOnCompletionListener{offset=chunk.end;if(autoContinue&&chunk.end<text.length){status="Continuando narración…";narrateAt?.invoke(chunk.end)}else if(chunk.end>=text.length){autoContinue=false;status="Llegaste al final del libro."}else status="Pausado en ${((chunk.end.toFloat()/text.length)*100).toInt()}%"};prepareAsync()}}catch(e:Exception){autoContinue=false;status="No pude narrar: ${e.message?:"error desconocido"}"}finally{generating=false}}}
fun startOrResume(){if(narratable==null)return;autoContinue=true;narrateAt?.invoke(offset)}
fun stopNarration(){autoContinue=false;runCatching{player?.stop()};runCatching{player?.release()};player=null;status="Narración detenida en $progress%."}
Scaffold(topBar={TopAppBar(title={Text(cleanBookTitle(book.title),maxLines=1,overflow=TextOverflow.Ellipsis)},navigationIcon={Button(onClick=onBack,modifier=Modifier.padding(horizontal=6.dp)){Text("Volver")}})}){padding->Column(Modifier.padding(padding).fillMaxSize()){Card(Modifier.fillMaxWidth().padding(12.dp)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Narración IA",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold);Text("Posición de narración: $progress%");LinearProgressIndicator(progress={progress/100f},Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(enabled=narratable!=null&&!generating&&!autoContinue,onClick={startOrResume()}){Text(if(generating)"Generando…" else if(offset==0)"Narrar" else "Reanudar")};if(autoContinue||player!=null)OutlinedButton(onClick={stopNarration()}){Text("Detener")};if(offset>0&&!autoContinue)OutlinedButton(enabled=!generating,onClick={offset=(offset-1200).coerceAtLeast(0);status="Retrocediste un tramo."}){Text("Atrás")}};Text(status,style=MaterialTheme.typography.bodySmall)}};if(book.isPdf)Box(Modifier.weight(1f)){PdfBookReader(book.uriString)}else if(book.textContent!=null)Column(Modifier.weight(1f).verticalScroll(rememberScrollState()).padding(20.dp)){Text(book.textContent,style=MaterialTheme.typography.bodyLarge)}else Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("Este formato todavía no puede narrarse.")}}}}
private data class NarrationChunk(val text:String,val end:Int)
private fun nextNarrationChunk(text:String,start:Int,max:Int=1150):NarrationChunk{if(start>=text.length)return NarrationChunk("",text.length);val hard=(start+max).coerceAtMost(text.length);if(hard==text.length)return NarrationChunk(text.substring(start),hard);val window=text.substring(start,hard);val candidates=listOf(window.lastIndexOf(". "),window.lastIndexOf("! "),window.lastIndexOf("? "),window.lastIndexOf("\n\n")).filter{it>max/2};val cut=(candidates.maxOrNull()?.plus(1)?:window.lastIndexOf(' ').takeIf{it>max/2}?:window.length);return NarrationChunk(window.substring(0,cut).trim(),start+cut)}
private fun cleanNarratableText(text:String)=text.replace(Regex("(?m)^\\s*\\d+\\s*$"),"").replace(Regex("[ \\t]+")," ").replace(Regex("\\n{3,}"),"\n\n").trim()
private fun extractPdfText(context:Context,uriString:String):String{val bytes=context.contentResolver.openInputStream(Uri.parse(uriString))?.use{it.readBytes()}?:error("No pude abrir el PDF");return PDDocument.load(bytes).use{doc->PDFTextStripper().apply{sortByPosition=true}.getText(doc).replace("\u0000","").trim()}}
@Composable private fun PdfBookReader(uriString:String){val context=LocalContext.current;var renderer by remember(uriString){mutableStateOf<PdfRenderer?>(null)};var descriptor by remember(uriString){mutableStateOf<ParcelFileDescriptor?>(null)};DisposableEffect(uriString){descriptor=runCatching{context.contentResolver.openFileDescriptor(Uri.parse(uriString),"r")}.getOrNull();renderer=descriptor?.let{runCatching{PdfRenderer(it)}.getOrNull()};onDispose{runCatching{renderer?.close()};runCatching{descriptor?.close()}}};val pdf=renderer?:return Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("Abriendo PDF…")};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(8.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){for(i in 0 until pdf.pageCount)remember(uriString,i){renderPdfPage(pdf,i,1.5f)}?.let{Image(it.asImageBitmap(),"Página ${i+1}",Modifier.fillMaxWidth(),contentScale=ContentScale.FillWidth)}}}
private fun renderPdfPageFromUri(context:Context,uri:String,index:Int,scale:Float):Bitmap?=runCatching{context.contentResolver.openFileDescriptor(Uri.parse(uri),"r")?.use{fd->PdfRenderer(fd).use{r->renderPdfPage(r,index,scale)}}}.getOrNull();private fun renderPdfPage(renderer:PdfRenderer,index:Int,scale:Float):Bitmap?=runCatching{renderer.openPage(index).use{p->Bitmap.createBitmap((p.width*scale).toInt(),(p.height*scale).toInt(),Bitmap.Config.ARGB_8888).also{b->b.eraseColor(android.graphics.Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY)}}}.getOrNull();private val BookDocument.isPdf get()=mimeType.contains("pdf",true)||title.endsWith(".pdf",true);private fun cleanBookTitle(title:String)=title.substringBeforeLast(".").replace('_',' ').replace(Regex("\\s+")," ").trim();private fun queryDisplayName(context:Context,uri:Uri):String?{var cursor:Cursor?=null;return try{cursor=context.contentResolver.query(uri,null,null,null,null);val c=cursor?:return null;val i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)c.getString(i)else null}finally{cursor?.close()}};private const val MALE_VOICE_ID="pNInz6obpgDQGcFmaJgB";private const val FEMALE_VOICE_ID="EXAVITQu4vr4xnSDxMaL"
