package app.bookflow.reader.core.data

import android.content.Context
import app.bookflow.reader.core.domain.NarrationPace
import app.bookflow.reader.core.domain.NarrationPlan
import app.bookflow.reader.core.domain.OfflineNarratorModel
import app.bookflow.reader.core.domain.RenderedVoiceSegment
import app.bookflow.reader.core.domain.VoiceRenderer
import app.bookflow.reader.core.domain.offlineNarratorModelFor
import com.k2fsa.sherpa.onnx.OfflineTts
import com.k2fsa.sherpa.onnx.OfflineTtsConfig
import com.k2fsa.sherpa.onnx.OfflineTtsModelConfig
import com.k2fsa.sherpa.onnx.OfflineTtsVitsModelConfig
import java.io.File
import java.security.MessageDigest
import java.util.UUID
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext

/**
 * Generates Spanish neural narration entirely on-device with Sherpa-ONNX and
 * two independent, single-speaker Piper high-quality models. No request leaves
 * the phone and no usage credit is consumed. Segments generated by the former cloud renderer are still
 * reused when their exact cache key is available.
 */
class OfflineNeuralVoiceRenderer(private val context: Context) : VoiceRenderer, AutoCloseable {
    private val renderMutex = Mutex()

    private val engines = mutableMapOf<OfflineNarratorModel, OfflineTts>()

    override suspend fun render(
        plan: NarrationPlan,
        @Suppress("UNUSED_PARAMETER") voiceId: String,
    ): RenderedVoiceSegment = withContext(Dispatchers.IO) {
        renderMutex.withLock {
            findLegacyCloudSegment(plan)?.let { return@withLock it }

            val narratorModel = offlineNarratorModelFor(plan.speakerId)
            val model = modelConfigFor(narratorModel)
            val passage = preparePassage(plan.passage.take(MAX_CHARS))
            val cacheKey = sha256(
                listOf(
                    model.version,
                    RENDER_PROFILE,
                    narratorModel,
                    plan.mood,
                    plan.pace,
                    plan.emotionalIntensity,
                    plan.pauseAfterSentencesMs,
                    passage,
                ).joinToString("|"),
            )
            val cacheDir = File(context.filesDir, LOCAL_CACHE_DIR).apply { mkdirs() }
            val cached = File(cacheDir, "$cacheKey.wav")
            if (cached.isFile && cached.length() > MIN_VALID_AUDIO_BYTES) {
                return@withLock RenderedVoiceSegment(cacheKey, cached.absolutePath, 0L)
            }

            val tts = engines.getOrPut(narratorModel) { createEngine(model) }
            val speed = when (plan.pace) {
                NarrationPace.SLOW -> 0.92f
                NarrationPace.MEDIUM -> 1.0f
                NarrationPace.FAST -> 1.12f
            }
            val audio = tts.generate(text = passage, sid = 0, speed = speed)
            check(audio.samples.isNotEmpty()) { "La voz local no produjo audio." }

            val temporary = File(cacheDir, ".$cacheKey-${UUID.randomUUID()}.wav")
            try {
                check(audio.save(temporary.absolutePath)) { "No pude guardar el audio local." }
                check(temporary.length() > MIN_VALID_AUDIO_BYTES) { "El audio local quedó incompleto." }
                if (!temporary.renameTo(cached)) {
                    temporary.copyTo(cached, overwrite = true)
                    temporary.delete()
                }
            } finally {
                if (temporary.exists()) temporary.delete()
            }

            val durationMs = audio.samples.size.toLong() * 1_000L / audio.sampleRate.coerceAtLeast(1)
            RenderedVoiceSegment(cacheKey, cached.absolutePath, durationMs)
        }
    }

    private fun createEngine(model: VoiceModelConfig): OfflineTts {
        val dataDir = prepareEspeakData(model)
        val threads = (Runtime.getRuntime().availableProcessors() / 2).coerceIn(2, 4)
        val config = OfflineTtsConfig(
            model = OfflineTtsModelConfig(
                vits = OfflineTtsVitsModelConfig(
                    model = "${model.assetDir}/${model.modelFile}",
                    tokens = "${model.assetDir}/tokens.txt",
                    dataDir = dataDir.absolutePath,
                    noiseScale = 0.667f,
                    noiseScaleW = 0.8f,
                    lengthScale = 1.0f,
                ),
                numThreads = threads,
                debug = false,
                provider = "cpu",
            ),
            maxNumSentences = 1,
            // Piper's default sentence gaps were too abrupt for long-form listening.
            // Keep punctuation in the passage and give sentence boundaries their
            // natural duration instead of compressing them to a quarter.
            silenceScale = 1.0f,
        )
        return OfflineTts(assetManager = context.assets, config = config)
    }

    private fun prepareEspeakData(model: VoiceModelConfig): File {
        val modelRoot = File(context.filesDir, "offline_tts/${model.version}")
        val destination = File(modelRoot, "espeak-ng-data")
        val marker = File(modelRoot, ".ready")
        if (
            marker.isFile &&
            marker.readText().trim() == model.archiveSha256 &&
            File(destination, "phondata").isFile
        ) {
            return destination
        }

        modelRoot.mkdirs()
        val stagingRoot = File(context.cacheDir, "offline-tts-${UUID.randomUUID()}")
        val stagingData = File(stagingRoot, "espeak-ng-data")
        try {
            copyAssetTree("${model.assetDir}/espeak-ng-data", stagingData)
            check(File(stagingData, "phondata").isFile) { "Faltan datos de pronunciación en español." }
            if (destination.exists()) destination.deleteRecursively()
            if (!stagingData.renameTo(destination)) {
                stagingData.copyRecursively(destination, overwrite = true)
            }
            marker.writeText(model.archiveSha256)
        } finally {
            stagingRoot.deleteRecursively()
        }
        return destination
    }

    private fun copyAssetTree(assetPath: String, destination: File) {
        val children = context.assets.list(assetPath).orEmpty()
        if (children.isEmpty()) {
            destination.parentFile?.mkdirs()
            context.assets.open(assetPath).use { input ->
                destination.outputStream().use { output -> input.copyTo(output) }
            }
            return
        }

        destination.mkdirs()
        children.forEach { child ->
            copyAssetTree("$assetPath/$child", File(destination, child))
        }
    }

    private fun findLegacyCloudSegment(plan: NarrationPlan): RenderedVoiceSegment? {
        val castVoiceId = if (plan.speakerId == FEMALE_SPEAKER) LEGACY_FEMALE_VOICE_ID else LEGACY_MALE_VOICE_ID
        val passage = plan.passage.take(LEGACY_MAX_CHARS)
        val key = sha256(
            "$castVoiceId|${plan.mood}|${plan.pace}|${plan.emotionalIntensity}|" +
                "${plan.pauseAfterSentencesMs}|$passage",
        )
        val cached = File(context.filesDir, "narration_cache/$key.mp3")
        return cached.takeIf { it.isFile && it.length() > MIN_VALID_AUDIO_BYTES }
            ?.let { RenderedVoiceSegment(key, it.absolutePath, 0L) }
    }

    private fun preparePassage(value: String): String = value
        .replace(Regex("[ \\t]+"), " ")
        .replace(Regex("\\n{3,}"), "\n\n")
        .trim()

    private fun sha256(value: String): String = MessageDigest.getInstance("SHA-256")
        .digest(value.toByteArray(Charsets.UTF_8))
        .joinToString("") { "%02x".format(it) }

    override fun close() {
        engines.values.forEach(OfflineTts::release)
        engines.clear()
    }

    private fun modelConfigFor(model: OfflineNarratorModel): VoiceModelConfig = when (model) {
        OfflineNarratorModel.MIRO_HIGH -> MIRO_MODEL
        OfflineNarratorModel.DANIELA_HIGH -> DANIELA_MODEL
    }

    private data class VoiceModelConfig(
        val version: String,
        val assetDir: String,
        val modelFile: String,
        val archiveSha256: String,
    )

    private companion object {
        const val RENDER_PROFILE = "high-quality-spanish-v1"
        const val LOCAL_CACHE_DIR = "offline_narration_cache"
        const val MAX_CHARS = 1_150
        const val LEGACY_MAX_CHARS = 1_200
        const val MIN_VALID_AUDIO_BYTES = 1_024L
        const val FEMALE_SPEAKER = "narrator_female"
        const val LEGACY_MALE_VOICE_ID = "pNInz6obpgDQGcFmaJgB"
        const val LEGACY_FEMALE_VOICE_ID = "21m00Tcm4TlvDq8ikWAM"
        val MIRO_MODEL = VoiceModelConfig(
            version = "piper-es-es-miro-high-v1",
            assetDir = "vits-piper-es_ES-miro-high",
            modelFile = "es_ES-miro-high.onnx",
            archiveSha256 = "15c7593c9e6eed29b48df983708672091c6ce3556485f351c2eb917cf3e5c2db",
        )
        val DANIELA_MODEL = VoiceModelConfig(
            version = "piper-es-ar-daniela-high-v1",
            assetDir = "vits-piper-es_AR-daniela-high",
            modelFile = "es_AR-daniela-high.onnx",
            archiveSha256 = "71cbf6b7f646ab74f3c51336151abef41e6c54467ac929ffdb19ed706a07dd7b",
        )
    }
}
